version: '3.8'

services:
  # Service de l'API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    # Variables d'environnement de production
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    restart: always

  # Service de base de données
  db:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

# Définition des volumes
volumes:
  mysql_data:
